language: php

sudo: required

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

addons:
    firefox: "47.0.1"

matrix:
    include:
        - php: 5.4
          env:
              - DEPENDENCIES='low'
        - php: 5.5
        - php: 5.6
          env:
              - SYMFONY_VERSION=2.6.*
        - php: 5.6
          env:
              - SYMFONY_VERSION=2.7.*
        - php: 5.6
          env:
              - SYMFONY_VERSION=2.8.*
        - php: 7.0

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - if [[ $SYMFONY_VERSION ]]; then composer require symfony/symfony:${SYMFONY_VERSION} -n --no-update; fi;
    - composer update $COMPOSER_FLAGS
    - "[ ! -f bin/selenium.jar ] && wget wget -O bin/selenium.jar http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar || true"

before_script:
    - nohup php -S localhost:8080 -t features/fixtures/project/web > /dev/null 2>&1 &
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - java -jar bin/selenium.jar > /dev/null 2>&1 &
    - sleep 5
    - features/fixtures/project/app/console assets:install features/fixtures/project/web --relative --symlink

script:
    - bin/phpspec run --format=pretty
    - bin/behat --no-snippets --format=progress --profile=travis

notifications:
    irc: "irc.freenode.org#fsi-open"
